package com.hopeinyang.zeroknowledge

const val SPLASH_SCREEN = "SplashScreen"
const val HOME_SCREEN = "HomeScreen"
const val DETAIL_SCREEN = "DetailScreen"
const val LOGIN_SCREEN = "LoginScreen"
const val SIGNUP_SCREEN ="SignupScreen"
const val SETTINGS_SCREEN = "SettingScreen"
const val ADMIN_SCREEN = "AdminScreen"
const val USER_LOGS_SCREEN = "UserActivityLogScreen"
const val SESSION_TIMEOUT="SessionTimeoutScreen"
const val OTP_SCREEN = "OtpScreen"
const val ACCOUNT_SCREEN = "AccountScreen"
const val ADD_PATIENT_SCREEN ="AddPatientScreen"
const val PATIENTS_LOG_SCREEN ="PatientsLogScreen"
const val REVERIFICATION_SCREEN ="ReverificationScreen"
const val ADD_PIN_SCREEN ="AddPinScreen"
const val GUIDELINE_SCREEN ="GuidelineScreen"
const val MANAGE_USER_SCREEN ="ManageUserScreen"
